spring:
  thymeleaf:
    cache: false
  datasource:
    password: 20010307lL.
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
server:
  port: 8080
  servlet:
    context-path: /hr

